name: Dependency Update Runner
on: 
    workflow_dispatch:

jobs:
    update-runner:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello, this is the dependency update runner!"

            - name: Check repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            
            - name: Install dependencies
              run: npm ci
            
            - name: Update dependencies
              run: |
                npm install -g npm-check-updates
                echo "Available updates" 
                ncu
                echo ""
                echo "Applying updates"
                ncu -u --reject "Faker,husky,marked" --target minor
                npm install
            
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                commit-message: "chore: update dependencies"
                title: "npm dependency update"
                body: | 
                    This PR updates the project dependencies to their latest versions.
                    Run by the Dependency Update Runner workflow.
                
                branch: chore/update-dependencies
                delete-branch: true
                